/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
	// By default, Docusaurus generates a sidebar from the docs folder structure
	tutorialSidebar: [{ type: "autogenerated", dirName: "." }],

	// But you can create a sidebar manually
	/*
  tutorialSidebar: [
    {
      type: 'category',
      label: 'Tutorial',
      items: ['hello'],
    },
  ],
   */
};

module.exports = sidebars;

export default {
  docs: [
    {
      type: 'category',
      label: 'Interpretation',
      link: {
        type: 'generated-index',
        title: 'Zapper Protocol',
        description: 'Learn about the most important Zapper concepts!',
        slug: '/docs/interpretation',
        keywords: ['guides'],
        image: '/img/docusaurus.png',
      },
      items: ['app-curation', 'app-token-interpretation', 'contract-position-interpretation', 'event-interpretation'],
    },
  ],
};
